default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prueba_twitter_development
  username: userdb
  password: ror2023
  host: localhost
  port: 5432